### PR TITLE
Add notebook for exploring cold bias in WRF data

### PR DESCRIPTION
**Pull request by kyleredilla**
This PR simply adds the notebook I used for exploring the cold bias in the WRF data, making multiple comparisons with the 12km NCAR dataset.

To review, just have a look. Paths are hard-coded and things may be a bit sloppy but I just wanted to put this somewhere - whether or not it continues to work probably won't matter much. Feel free to try running it (Atlas) and committing suggestions if either of you would like to expand it.

### CODE REVIEW

**Comment by Joshdpaul** [comment]
Kyle, I was able to run this notebook without issue 👍🏻

The plots do a good job of showing the cold bias in Valdez and Palmer, which is presumably due to glacier proximity? I assume the meeting this notebook was created for has passed....but if this issue is revisited in the future, a basic map with grid cells / glaciers for these locations might support the glacier proximity hypothesis.

A question on your code: Why did you use "nearest" method in the ```extract_wrf``` and ```extract_wrf_proj``` functions, but the euclidean distance/RMSE in the ```extract_ncar``` and ```extract_ncar_proj``` functions?

**Comment by kyleredilla** [comment]
Awesome! Great feedback. 

The reason for that is because that NCAR data does not have a projection defined in the files, so I would have needed extra code to be able to define a CRS to reproject the extraction lat/lon to, to yield the x/y values for using the `.sel` method. Since they already have the lat/lon grids as variables (2D arrays), I just had to find the closest pixel using both of those, since they are irregular grids. The WRF data has the projection defined as an attribute so it is easier to reproject the lat/lon to that CRS for extraction.

**Comment by Joshdpaul** [comment]
OK that makes perfect sense. Thanks for explaining! Can I merge this or do you want Charlie to review also?

**Comment by kyleredilla** [comment]
You can go ahead and merge Josh, @charparr can look afterwards, it's not even really important, we didn't even end up referencing this that much iirc.

**Pull request merged**
